### PR TITLE
fddev: print genesis hash

### PR DESCRIPTION
**Pull request by ripatel-fd**

### CODE REVIEW

**Review by alpeng-jump — DISMISSED** [review]

**Comment by ptaffet-jump** [comment]
This function already exists here: https://github.com/firedancer-io/firedancer/blob/7a34721bb44f482ce716aeb8b7a71c765860b060/src/app/fddev/genesis_hash.h#L9

**Comment by ripatel-fd** [comment]
@alpeng-jump Would you like to take over and finish this PR? Let's deduplicate the logic to compute the shred version and genesis hash as Philip suggested.

**Review by ptaffet-jump — APPROVED** [review]
Approving on behalf of @ripatel-fd

**Comment by alpeng-jump** [comment]
Sorry was asleep then - thanks for picking up the changes @ripatel-fd

**Pull request merged**
