### PR TITLE
Add Murmur3-32 hash function

### PR DESCRIPTION
**Pull request by ripatel-fd**
Required for the sBPF ELF loader

### CODE REVIEW

**Comment by ripatel-fd** [comment]
@lheeger-jump It turns out we both implemented the same Murmur3-32 hash function. Please feel free to push anything missing to this PR and I'll squash.

**Comment by lheeger-jump** [comment]
Yes I will likely smush our two versions together cause there are some cute things in both

**Comment by lheeger-jump** [comment]
This weekend

**Comment by ripatel-fd** [comment]
@lheeger-jump Thanks 🙏 No rush, can wait until next week too.

**Review by lheeger-jump — APPROVED** [review]

**Pull request merged**
