### PR TITLE
flamenco, vm: remove obselete apis from fd_account_old

### PR DESCRIPTION
**Pull request by topointon-jump**
This is most of the way towards being able to remove fd_account_old

### CODE REVIEW

**Review by jumpsiegel — DISMISSED** [review]

**Review by ibhatt-jumptrading — DISMISSED** [review]

**Review by ripatel-fd — APPROVED** [review]

**Review by ripatel-fd — CHANGES_REQUESTED** [review]
```
src/flamenco/runtime/program/fd_bpf_loader_v3_program.c:811:11: error: implicit declaration of function ‘fd_account_set_executable2’; did you mean ‘fd_account_set_executable’? [-Werror=implicit-function-declaration]
```

**Comment by topointon-jump** [comment]
@ripatel-fd this pr depends on https://github.com/firedancer-io/firedancer/pull/2200 being merged

**Comment by ripatel-fd** [comment]
@topointon-jump If you set the base branch of this PR onto the other PR then we can streamline the review of both. GitHub will automatically change the base branch of this PR when the other PR is merged without breaking approvals. Like Gerrit.

**Comment by topointon-jump** [comment]
Closing for now

**Pull request closed without merging**
