### PR TITLE
Speedup funk record table with memoize

### PR DESCRIPTION
**Pull request by asiegel-jt**

### CODE REVIEW

**Review by lidatong — COMMENTED** [review]
i'm ok with this change but needs @kbowers-jump approval for change to util

**Review by kbowers-jump — APPROVED** [review]
Some polishing to consider in the future (not important enough to hold up this PR):
- Annotate hash == ele->MAP_HASH branches with likely / unlikely.
- Eliminate the list_private_idx as memoization seems to eliminate the need for it.
- Rename the unit test to test_map_giant_memo (instead of mem).
- Added extra validation of the memo in the unit test.
- Clean up query2 (unrelated to this PR but it is just a const cast variant of query).
- Add static assert that the funk txn footprint is the expect amount (much as there current is for the funk rec footprint).

**Review by lidatong — APPROVED** [review]

**Review by lheeger-jump — APPROVED** [review]
I am a little dubious of how this actually speeds things up. Can you please post a benchmark of the improvement (before and after)?

**Review by lheeger-jump — CHANGES_REQUESTED** [review]
Sorry meant to set this as request changes

**Review by lheeger-jump — DISMISSED** [review]

**Comment by asiegel-jt** [comment]
> Sorry meant to set this as request changes

It saves 6 seconds out of 330 in my test. Not impressive but it doesn't hurt.

**Review by lidatong — APPROVED** [review]

**Pull request merged**
