### PR TITLE
Import nanopb 0.4.7

### PR DESCRIPTION
**Pull request by ripatel-fd**
The Firedancer runtime branch currently uses Nanopb for handling Protobuf messages.

### CODE REVIEW

**Comment by mmcgee-jump** [comment]
The NOTICE says

> 'src/flamenco/nanopb' is currently a modified copy of the Nanopb library at https://jpa.kapsi.fi/nanopb/ (imported ca 2023-Sep).

But I had a hard time figuring out what the changes were. Is it modified? Can we use a .patch file applied at build time for these modifications? It will make review easier and save some merge and other headaches later.

**Comment by ripatel-fd** [comment]
> The NOTICE says
> 
> > 'src/flamenco/nanopb' is currently a modified copy of the Nanopb library at https://jpa.kapsi.fi/nanopb/ (imported ca 2023-Sep).
> 
> But I had a hard time figuring out what the changes were. Is it modified? Can we use a .patch file applied at build time for these modifications? It will make review easier and save some merge and other headaches later.

Good idea 👍

**Comment by jumpsiegel** [comment]
https://github.com/firedancer-io/firedancer/issues/920

**Comment by ripatel-fd** [comment]
~~@mmcgee-jump I'm going to restore this branch to its original state and move your changes to `mmcgee/nanopb`.~~

**Review by mmcgee-jump — APPROVED** [review]

**Pull request merged**
