### PR TITLE
Copy gossip and types from private

### PR DESCRIPTION
**Pull request by asiegel-jt**

### CODE REVIEW

**Comment by ripatel-fd** [comment]
@asiegel-jt Could you split out the commits for updating types and adding the gossip implementation?

**Comment by ripatel-fd** [comment]
@mmcgee-jump FYI fd_types does not offer safe deserialization. It will crash on untrusted input, and we don't have fuzz coverage. IMHO types should be reworked before we include gossip in 1.5.

**Comment by mmcgee-jump** [comment]
Yeah, I took a read through and this is probably not yet ready for use in 1.5

**Comment by asiegel-jt** [comment]
> @asiegel-jt Could you split out the commits for updating types and adding the gossip implementation?

This seems unnecessary. It's separated by directory.

**Comment by ripatel-fd** [comment]
> > @asiegel-jt Could you split out the commits for updating types and adding the gossip implementation?
> 
> This seems unnecessary. It's separated by directory.

Squashing everything into a single commit makes it harder to revert individual changes and loses information who originally authored this code.

**Comment by jumpsiegel** [comment]
Lets get the types stuff merged in as its own PR since it looks like people want it to be fuzzed and bullet proof.  Once that is merged/updated... gossip looks like it will be a no brainer

**Pull request closed without merging**
