### PR TITLE
fuzz, flamenco, conformance: scripts for building and running conformance and conformance targets

### PR DESCRIPTION
**Pull request by mjain-jump**
You can now build and run `solana-conformance` with `solfuzz-agave` targets built using `contrib/conformance/*sh`. Usage details will be provided [here](https://github.com/firedancer-io/firedancer-private/wiki/Debugging-Bank-Hash-Mismatches).

### CODE REVIEW

**Comment by kbhargava-jump** [comment]
we need to centralize this a bit better. we currently also have `src/flamenco/runtime/tests/run_conformance_tests.sh` and `contrib/ledger-tests/ledger_conformance.sh`

**Comment by kbhargava-jump** [comment]
lets wait on this and centralize it with @alpeng-jump

**Comment by alpeng-jump** [comment]
let's centralize this with ledger conformance, more details in chat

**Review by alpeng-jump — APPROVED** [review]

**Review by alpeng-jump — CHANGES_REQUESTED** [review]
do not merge

**Comment by ripatel-fd** [comment]
Closing for now as a stale PR

**Pull request closed without merging**
