### PR TITLE
remove custom format string specifiers

### PR DESCRIPTION
**Pull request by two-heart**
Custom format string specifiers conflict with compile time format string checks. Drive by: fix all format string bugs in the codebase and formating

### CODE REVIEW

**Review by ripatel-fd — APPROVED** [review]

**Comment by riptl** [comment]
The macros should be updated to handle a NULL pointer gracefully. (As %32J previously did) I think lack thereof causes the segfault in the ledger tests.

**Comment by ripatel-fd** [comment]
Fixes https://github.com/firedancer-io/auditor-internal/issues/220

**Comment by riptl** [comment]
Approving, looks great (don't have permissions to actually approve on the work phone, so someone else from the team will have to review)

Thank you for getting this one over the line. 

@jumpsiegel @lheeger-jump Would you mind reviewing?

We ended up renaming the new base58 macro to underline the consequences of using alloca.

**Comment by jumpsiegel** [comment]
if I fix the merge conflict, I can't then approve the PR...

**Comment by riptl** [comment]
@two-heart Could you fix the merge conflict? Rebase or merge commit, either works. Thank you

**Review by ripatel-fd — APPROVED** [review]

**Pull request merged**
