### PR TITLE
fix: fddev monitor tries to join shmem without init

### LINKED ISSUE #3607: Investigate why fddev fails to allocate shared memory region for fd_net_quic.wksp
image

Version: v0.202.20016 

Config:
```toml
name = "fd-anoushk"
user = "ubuntu"

[development]
    sandbox = false
    [development.netns]
        enabled = true
[tiles.net]
    interface = "veth_test_xdp_0"

[rpc]
    port = 8899
    full_api = true
    private = true
```

### PR DESCRIPTION
**Pull request by anoushk1234**
Fixes #3607 and #3586

### CODE REVIEW

**Comment by mmcgee-jump** [comment]
Thanks for the contribution! Can you clean the commit stack (rebase/remove the merge commit).

**Comment by anoushk1234** [comment]
@mmcgee-jump Done!

**Review by mmcgee-jump — APPROVED** [review]

**Comment by mmcgee-jump** [comment]
Sorry can you also rebase on main to fix the broken test, thanks!

**Comment by anoushk1234** [comment]
> Sorry can you also rebase on main to fix the broken test, thanks!

done!

**Comment by mmcgee-jump** [comment]
Thanks for the contribution!

**Pull request merged**
