### PR TITLE
util: add fd_rdrand for x86

### PR DESCRIPTION
**Pull request by ripatel-fd**

### CODE REVIEW

**Comment by mmcgee-jump** [comment]
Caller needs to be changed to check the return code.

**Comment by ripatel-fd** [comment]
> Caller needs to be changed to check the return code.

Which caller? The PR only adds the method and a test

**Comment by mmcgee-jump** [comment]
Huh, must have looked at the wrong PR.

**Comment by ripatel-fd** [comment]
> Huh, must have looked at the wrong PR.

No sorry for gaslighting you. I removed the offending commit a few days ago.

**Pull request merged**
