### PR TITLE
Tidy up runtime dependency graph

### PR DESCRIPTION
**Pull request by ripatel-fd**
- **runtime: split parts of fd_runtime.c into fd_runtime_init.c**
- **runtime: split executor error codes into fd_executor_err.h**
- **runtime: Optimize imports**

### CODE REVIEW

**Comment by ripatel-fd** [comment]
Marking as high priority because people have been getting a bunch of link errors with libsecp256k1.a

**Comment by jumpsiegel** [comment]
My concern about this is it is going to touch a great deal of the same files of the vm belt sanding branch which is days/minutes away from being merged.... I see cu consuming functions/etc being moved around.  Could we hold off on merging this until tom merges the vm stuff?

**Comment by ripatel-fd** [comment]
> My concern about this is it is going to touch a great deal of the same files of the vm belt sanding branch which is days/minutes away from being merged.... I see cu consuming functions/etc being moved around. Could we hold off on merging this until tom merges the vm stuff?

Tom mentioned on Slack that there don't appear to be many conflicts. @topointon-jump can you confirm here?

**Comment by jumpsiegel** [comment]
tom says all good.. :)

**Comment by topointon-jump** [comment]
@jumpsiegel I had a look and it's fine to merge this, don't wait on me :)

**Review by jumpsiegel — APPROVED** [review]

**Review by lheeger-jump — APPROVED** [review]

**Pull request merged**
