### PR TITLE
fix: rw lock misbehavior

### PR DESCRIPTION
**Pull request by lheeger-jump**

### CODE REVIEW

**Comment by mmcgee-jump** [comment]
Also revert the volatile change (or do it properly with FD_VOLATILE ( ... ))

**Review by mmcgee-jump — CHANGES_REQUESTED** [review]
.

**Comment by jumpsiegel** [comment]
What does the "." comment mean?

**Comment by lheeger-jump** [comment]
Fixed

**Review by mmcgee-jump — APPROVED** [review]

**Pull request merged**
