### PR TITLE
shmem: fix support for kernels without NUMA

### LINKED ISSUE #292: void

### PR DESCRIPTION
**Pull request by ripatel-fd**
Fixes #292 

Adds back sysfs-mocking NUMA test

### CODE REVIEW

**Comment by abebeos** [comment]
```sh
INFO    2023-04-26 22:24:15.936870500 GMT+00  23969:23969  [user]:d81519854489:f0   [app]:test_numa_linux:0    src/util/tile/fd_tile_threads.cxx(667)[fd_tile_private_boot]: fd_tile: boot success
ERR     2023-04-26 22:24:15.937434700 GMT+00  23969:23969  [user]:d81519854489:f0   [app]:test_numa_linux:0    src/util/shmem/test_numa_linux.c(136)[test_numa_linux]: FAIL: 0==unshare( CLONE_NEWUSER|CLONE_NEWNS )
ERR     2023-04-26 22:24:15.949617600 GMT+00  23969:23969  [user]:d81519854489:f0   [app]:test_numa_linux:0    src/util/shmem/test_numa_linux.c(187)[main]: FAIL: WEXITSTATUS( status )==0
make: *** [src/util/shmem/Local.mk:15: run-test_numa_linux] Error 1
```

**Comment by ripatel-fd** [comment]
@abebeos Which kernel version and operating system are you running on?

**Comment by abebeos** [comment]
>> on an dev-container (ubuntu-22.04, docker-host: Win10Pro/Hyper-V)

So nothing special (container is fresh).

```
root@d81519854489:~/fire# uname -a
Linux d81519854489 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by abebeos** [comment]
any update on this from your side? 

Me stuck:
- I failed with https://github.com/abebeos/firedancer/issues/1
- I failed with https://github.com/firedancer-io/firedancer/blob/main/contrib/docker/ubi9.Dockerfile
  - seems out-of-sync with main readme instructions
  - strange problems with ubi9 (ubi9 misses "gettext-devel flex bison", asks for registration)
- A workaround to use github CI for now: I cannot simply "clone" your github-CI, as it uses a non-standard runner.

**Comment by ripatel-fd** [comment]
> any update on this from your side?

@abebeos No updates for now. Development is currently only supported on bare-metal with a recent Linux kernel. The error message you are seeing stems from a Linux kernel without NUMA support. I don't have an environment up to reproduce the same kind of errors, but it looks like it will require non-trivial changes to our memory locality logic in src/util/shmem. Unfortunately, I don't have an estimate for when that will be fixed. 

> FAIL: 0==unshare( CLONE_NEWUSER|CLONE_NEWNS )

The unshare error stems from lack of support for unprivileged namespaces. I think this is a consequence of using Docker. The assertion in this PR should be changed to just skip the test on a permission error. Other tests should not fail in the same way.

**Comment by abebeos** [comment]
I see. You are aware this limits the potential contributor base.

Just one last thing: did you manage at any time to run the build/tests on github on a standard-runner? (just so I avoid trying)

**Comment by ripatel-fd** [comment]
> did you manage at any time to run the build/tests on github on a standard-runner?

@abebeos Yes, we used GitHub-managed runners in the past. However, those came without SHA-NI (see #311) and have a broken real-time clock which results in sporadic test failures (the fd_tango tests attempt to detect broken clock_gettime). Unit tests will not pass on these runners without modifications.

**Comment by ripatel-fd** [comment]
Closing for now. No immediate interest to support kernels without NUMA. Might reopen later on.

**Pull request closed without merging**
